executors:
  node:
    docker:
      - image: circleci/node:8

version: 2.1

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Install  elm
          command: 'sudo npm install -g elm --unsafe-perm=true --allow-root'
      - run: elm make
      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./public -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
